### ISSUE TITLE
Error Demjson

### ISSUE THREAD

**Issue by Bebettox** [ouassimBenMosbah/Sports-betting#11]
Au lancement de la commande python interface_pysimplegui.py j'obtiens le message suivant :
![image](https://github.com/ouassimBenMosbah/Sports-betting/assets/155632437/c34831a8-15f1-44af-a1a8-789f91189f70)

J'ai du passer manuellement plusieurs modules (pip install) avant d'arriver sur ce blocage

**Comment by Bebettox** [comment]
C'est bon j'ai du modifier un fichier concernant le bookmaker Betway pour le forcer en demjson3

**Comment by ouassimBenMosbah** [comment]
Je n'avais pas vu l'issue. Tu as pu lancer le projet ?
