### ISSUE TITLE
impossible de recuperer les cotes 

### ISSUE THREAD

**Issue by Galban57** [ouassimBenMosbah/Sports-betting#14]
Je n'arrive pas a récupérer les cotes peu importe les books coches (sauf netbet et Zebet). j'ai bien suivi le tuto comme expliqué sauf que j'ai remplacé le module demjson en demjson3, j'ai mis a jour urllib3 et j'ai supprimé les lignes d'edge sur le fichier webdriver.py car j'avais un message d'erreur lors du lancement **(ImportError: cannot import name 'EdgeOptions' from 'selenium.webdriver' (C:\Python\Lib\site-packages\selenium\webdriver\__init__.py). Did you mean: 'IeOptions'?)**. J'arrive bien a lancer l'interface mais aucune cote d'accessible.

**Comment by Galban57** [comment]
![Capture d'écran 2024-02-05 011505](https://github.com/ouassimBenMosbah/Sports-betting/assets/158842076/c8fb69bb-0c44-40ef-9079-f5b349d7e502)

**Comment by ouassimBenMosbah** [comment]
Est-ce que tu as réussi à résoudre le problème ?

**Comment by Galban57** [comment]
Oui j'ai enfin compris, j'utilisais l'ancienne version du projet donc aucune MAJ n'etait possible.

**Comment by BattlePuppy** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
MasterDimmy, @LakeSky, @khelle, @sampleblood, @tn606024, @linchuche, @trongham, @sachess, @kimdj, @ricardoorellana, @imnolte, @LeeDongHyeok, @shoopman, @danielreinhardt1, @dabasir, @amitb2hk, @zby810, @onigirisan, @TeeTheCoder1, @zBl4ckUser, @gabrielfern, @AdrianDSW, @pocotan001, @PrincessEve, @carlosrogue, @midacts, @zbdxwl, @dyba, @abx42, @PeterVatistas, @juicelzl, @guweigang, @gravitycode, @cdrrazan, @jamiedevsandbox, @stephenbunch, @PShuvaev, @capyvara, @sdzyba, @e-flex, @tbckr, @hnrq, @Dubhghlas, @fiftynineseconds, @Nate-Wilkins, @yujinw, @fredericksilva, @twumm, @keizerzilla, @gkim0101
